### ISSUE TITLE
Maestro does not identify containers restarted by docker upon reboot

### ISSUE THREAD

**Issue by hamiltont** [signalfuse/maestro-ng#102]
I've got this in my YAML: 

```
  sonarr:
    image: tuxeh/sonarr:develop
    instances:
      sonarr:
        ship: media
        restart: always
        ports: {shttp: 8989}
        lifecycle:
          running: [{type: tcp, port: shttp}]
        volumes:
          /volumes/media:                      <snip>
          /volumes/config:                      <snip>
          /volumes/completed:               <snip>
```

I rebooted the server, and Docker happily restarted this container as per the restart settings. 

However, now running `maestro -f myfile.yaml start` fails (as shown below) because the port is already bound and maestro doesn't realize that the running container is the one defined in my yaml. I can manually fix this - just run `docker stop` on the offending container and then I can run `maestro start` as expected, but if there's any way to address this edge case inside maestro that would obviously be better. 

```
  5. sonarr               sonarr          media                e6fdb68         failed to start container!
Traceback (most recent call last):
  File "/usr/local/bin/maestro", line 9, in <module>
    load_entry_point('maestro==0.1.7', 'console_scripts', 'maestro')()
  File "/usr/local/lib/python2.7/dist-packages/maestro/__main__.py", line 88, in main
    getattr(c, options.command)(**vars(options))
  File "/usr/local/lib/python2.7/dist-packages/maestro/maestro.py", line 210, in start
    plays.Start(containers, self._registries, refresh_images).run()
  File "/usr/local/lib/python2.7/dist-packages/maestro/plays.py", line 184, in run
    result = self._start_container(o, container)
  File "/usr/local/lib/python2.7/dist-packages/maestro/plays.py", line 318, in _start_container
    privileged=container.privileged)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 742, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 115, in _raise_for_status
    raise APIError(e, response, explanation=explanation)
docker.client.APIError: 500 Server Error: Internal Server Error ("Cannot start container e6fdb680e2f18e6a244a4e71964c28f201111347e8546ee9a547dedacf45db50: Bind for 0.0.0.0:8989 failed: port is already allocated")
```

**Comment by mpetazzoni** [comment]
I believe this is fine now, at least with Docker 1.5.0 (haven't tested earlier versions), containers correctly keep the same name when the Docker daemon is restarted.
