### ISSUE TITLE
"Container status could not be obtained after creation!"

### ISSUE THREAD

**Issue by nistvan86** [signalfuse/maestro-ng#117]
Today I've tried to upgrade to Docker 1.5.0 on my server and decided to do a full stack upgrade (dist-upgrade, Maestro, Docker). Since then Maestro is unable to check status of freshly created containers, but this happens randomly during execution (not by the same container each time).

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/maestro/__main__.py", line 207, in main
    getattr(c, options.command)(**vars(options))
  File "/usr/local/lib/python2.7/dist-packages/maestro/maestro.py", line 299, in start
    ignore_dependencies, concurrency, reuse))
  File "/usr/local/lib/python2.7/dist-packages/maestro/maestro.py", line 229, in _audit_play
    exceptions.raise_with_tb()
  File "/usr/local/lib/python2.7/dist-packages/maestro/maestro.py", line 217, in _audit_play
    play.run()
  File "/usr/local/lib/python2.7/dist-packages/maestro/plays/__init__.py", line 146, in run
    self._end()
  File "/usr/local/lib/python2.7/dist-packages/maestro/plays/__init__.py", line 138, in _end
    exceptions.raise_with_tb(self._error)
  File "/usr/local/lib/python2.7/dist-packages/maestro/plays/__init__.py", line 95, in act
    task.run()
  File "/usr/local/lib/python2.7/dist-packages/maestro/plays/tasks.py", line 130, in run
    result = self._create_and_start_container()
  File "/usr/local/lib/python2.7/dist-packages/maestro/plays/tasks.py", line 208, in _create_and_start_container
    'Container status could not be obtained after creation!')
OrchestrationException: Container status could not be obtained after creation!
```

I've tried to downgrade to Docker 1.4.1 but nothing changes.
Maestro is the latest development version: maestro-0.2.4.2-dev

Earlier i had issues with python-requests and docker-py version, so maybe this information helps to solve the issue:
* requests-2.4.3
* docker-py-0.7.2

Server is an Ubuntu Server 14.04.

**Comment by nistvan86** [comment]
Nevermind. I've forgot that on this machine we are using aufs storage for Docker and after dist-upgrading there was no kernel-extras installed, so Docker reverted to devicemapper. After installing extras and cleaning Docker's directory the problem went away.

**Comment by mpetazzoni** [comment]
Glad you figured it out!
