### ISSUE TITLE
Private registry pull not work

### ISSUE THREAD

**Issue by iHile** [signalfuse/maestro-ng#124]
i define my registry:
```
registries:
  my-private-registry:
    registry: https://docker-registry.xxx.com/v1/
    username: dev
    password: xxx
    email:
```

and image as:

```
image: my-private-registry/mongodb:3.0.3
```

In stdout:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/maestro/__main__.py", line 209, in execute
    getattr(c, options.command)(**vars(options))
  File "/usr/local/lib/python2.7/site-packages/maestro/maestro.py", line 306, in pull
    ignore_dependencies, concurrency))
  File "/usr/local/lib/python2.7/site-packages/maestro/maestro.py", line 262, in _audit_play
    exceptions.raise_with_tb()
  File "/usr/local/lib/python2.7/site-packages/maestro/maestro.py", line 250, in _audit_play
    play.run()
  File "/usr/local/lib/python2.7/site-packages/maestro/plays/__init__.py", line 147, in run
    self._end()
  File "/usr/local/lib/python2.7/site-packages/maestro/plays/__init__.py", line 139, in _end
    exceptions.raise_with_tb(self._error)
  File "/usr/local/lib/python2.7/site-packages/maestro/plays/__init__.py", line 96, in act
    task.run()
  File "/usr/local/lib/python2.7/site-packages/maestro/plays/tasks.py", line 408, in run
    percentage = self._update_pull_progress(dlstatus)
  File "/usr/local/lib/python2.7/site-packages/maestro/plays/tasks.py", line 425, in _update_pull_progress
    last['errorDetail']['message']))
OrchestrationException: Pull of image my-private-registry/mongodb:3.0.3 failed: Error: image my-private-registry/mongodb:3.0.3 not found
```

In docker logs:

```

time="2015-05-25T13:35:05+03:00" level=debug msg="Calling POST /images/create" 
time="2015-05-25T13:35:05+03:00" level=info msg="POST /v1.10/images/create?tag=3.0.3&fromImage=my-private-registry%2Fmongodb" 
time="2015-05-25T13:35:05+03:00" level=info msg="+job pull(my-private-registry/mongodb, 3.0.3)" 
time="2015-05-25T13:35:05+03:00" level=info msg="+job resolve_repository(my-private-registry/mongodb)" 
time="2015-05-25T13:35:05+03:00" level=info msg="-job resolve_repository(my-private-registry/mongodb) = OK (0)" 
time="2015-05-25T13:35:05+03:00" level=debug msg="pulling image from host \"docker.io\" with remote name \"my-private-registry/mongodb\"" 
time="2015-05-25T13:35:05+03:00" level=debug msg="pinging registry endpoint https://index.docker.io/v1/" 
time="2015-05-25T13:35:05+03:00" level=debug msg="attempting v1 ping for registry endpoint https://index.docker.io/v1/" 
time="2015-05-25T13:35:05+03:00" level=debug msg="pulling v2 repository with local name \"my-private-registry/mongodb\"" 
time="2015-05-25T13:35:05+03:00" level=debug msg="pinging registry endpoint https://registry-1.docker.io/v2/" 
time="2015-05-25T13:35:05+03:00" level=debug msg="attempting v2 ping for registry endpoint https://registry-1.docker.io/v2/" 
time="2015-05-25T13:35:05+03:00" level=debug msg="https://registry-1.docker.io/v2/ -- HEADERS: map[User-Agent:[docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/2.6.32-504.16.2.el6.centos.plus.x86_64 os/linux arch/amd64]]" 
time="2015-05-25T13:35:05+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-05-25T13:35:06+03:00" level=debug msg="Getting authorization for my-private-registry/mongodb [pull]" 
time="2015-05-25T13:35:06+03:00" level=debug msg="Pulling tag from V2 registry: \"3.0.3\"" 
time="2015-05-25T13:35:06+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/my-private-registry/mongodb/manifests/3.0.3" 
time="2015-05-25T13:35:06+03:00" level=debug msg="https://registry-1.docker.io/v2/my-private-registry/mongodb/manifests/3.0.3 -- HEADERS: map[User-Agent:[docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/2.6.32-504.16.2.el6.centos.plus.x86_64 os/linux arch/amd64]]" 
time="2015-05-25T13:35:06+03:00" level=debug msg="Getting bearer token with map[realm:https://auth.docker.io/token service:registry.docker.io] for " 
time="2015-05-25T13:35:06+03:00" level=debug msg="https://auth.docker.io/token -- HEADERS: map[User-Agent:[docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/2.6.32-504.16.2.el6.centos.plus.x86_64 os/linux arch/amd64]]" 
time="2015-05-25T13:35:06+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-05-25T13:35:07+03:00" level=error msg="Error from V2 registry: Authentication is required." 
time="2015-05-25T13:35:07+03:00" level=debug msg="image does not exist on v2 registry, falling back to v1" 
time="2015-05-25T13:35:07+03:00" level=debug msg="pulling v1 repository with local name \"my-private-registry/mongodb\"" 
time="2015-05-25T13:35:07+03:00" level=debug msg="[registry] Calling GET https://index.docker.io/v1/repositories/my-private-registry/mongodb/images" 
time="2015-05-25T13:35:07+03:00" level=debug msg="https://index.docker.io/v1/repositories/my-private-registry/mongodb/images -- HEADERS: map[User-Agent:[docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/2.6.32-504.16.2.el6.centos.plus.x86_64 os/linux arch/amd64]]" 
time="2015-05-25T13:35:07+03:00" level=debug msg="hostDir: /etc/docker/certs.d/index.docker.io" 
Error: image my-private-registry/mongodb:3.0.3 not found
time="2015-05-25T13:35:08+03:00" level=info msg="-job pull(my-private-registry/mongodb, 3.0.3) = ERR (1)" 
```

```
maestro-0.2.6.1
```

What i do wrong ?

**Comment by mpetazzoni** [comment]
Maestro should have tried to log in to your private registry before doing the pull. Do you have the Docker daemon log snipped for that as well? It should be right before the `POST /images/create`.

If it didn't log in, it could mean that it was not able to map that image name to the private registry you have defined in your YAML, even though I'm not sure how this would happen. Could you post the full actual names of your image, and the un-edited `registries` section from your YAML?

**Comment by iHile** [comment]
On nginx front-end for registry i not see any requests in logs. 

Before ```POST /images/create``` in log nothing... 

I use pretty passowrd like [a-zA-z0-9] and empty email.

```
registries:
  my-private-registry:
    registry: https://docker-registry.testdomain.net/v1/
    username: dev
    password:
    email:
```

Pull directly from node works fine.

**Comment by mpetazzoni** [comment]
Do you see Maestro trying to log in to a registry before pulling the image?

**Comment by iHile** [comment]
I see:

```
logging in to https://docker-registry.....
```

After run maestro pull

**Comment by mpetazzoni** [comment]
Ok, so at least it's trying. I think the problem is that you have a `~/.dockercfg` file with an invalid entry for your private registry. This would make `docker-py` not actually try to log in.

You can force a re-login, either by removing your `~/.dockercfg` file, or if you don't want to do that, by adding `reauth: true` to your registry configuration in your YAML.

**Comment by bradjones1** [comment]
My experience has been that while you can name a private registry, I've only been able to list it in the image: specification of an instance using the FQDN. private-registry-name/image doesn't seem to work, but my.repository.local/image does.

Kinda makes sense in that there's no real way to differentiate between the former case and a docker hub repository name? If I can confirm how exactly this is supposed to work I can help with a documentation patch?

**Comment by mpetazzoni** [comment]
This is not a MaestroNG issue. Your image name has to be a valid Docker image name, even when using a private registry.
