### ISSUE TITLE
ValueError: No JSON object could be decoded when starting with docker 1.3.0

### ISSUE THREAD

**Issue by rwestgeest** [signalfuse/maestro-ng#86]
I have upgraded docker (boot2docker) to 1.3. After that, maestro start and pull yield an error : "No JSON object could be decoded"

Can anyone hint towards the root cause of this. Is this a bug or some incompatibility issue? 

Traceback (most recent call last):
  File "/Users/rob/Library/Python/2.7/lib/python/site-packages/maestro/__main__.py", line 200, in main
    getattr(c, options.command)(**vars(options))
  File "/Users/rob/Library/Python/2.7/lib/python/site-packages/maestro/maestro.py", line 290, in start
    ignore_dependencies, concurrency))
  File "/Users/rob/Library/Python/2.7/lib/python/site-packages/maestro/maestro.py", line 223, in _audit_play
    raise e

ValueError: No JSON object could be decoded

my test yaml:

    name: SessionServer
    registries:
    ships:
      local:
        ip: '192.168.59.103'
        docker_port: 2376
        timeout: 60
    services:
      registry:
        image: 'registry'
        instances:
          registry:
            ports: {cache_port: "5000:5000"}
            ship: local

**Comment by mpetazzoni** [comment]
This seems like it was a problem only with a certain combination of Docker daemon and `docker-py` and is unrelated to Maestro.
